services:
  api:
    build:
      context: .
      dockerfile: deploy/prod.dockerfile
    # container_name: tripteller-api
    env_file:
      - .production.env
    networks:
      - tripteller-network
    restart: unless-stopped
    ports:
      - '3000:3000'
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'https://api.trip-teller.com/health-check']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  nginx:
    image: nginx:stable-alpine
    container_name: tripteller-nginx
    ports:
      - '80:80'
    networks:
      - tripteller-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    depends_on:
      - api

networks:
  tripteller-network:
    driver: bridge
